### ISSUE TITLE
how can deploy multi-master cluster

### ISSUE THREAD

**Issue by rmccomb-bnet** [yamamoto-febc/terraform-provider-rke#104]
I've tried the following config for nodes and its only works when I have 1 controlplane, etcd node but whenever I add more than one, `kubectl` is unable to talk to the api-server
`nodes = [
    {
      address = "${module.nodes.addresses[0]}"
      user    = "${module.nodes.ssh_username}"
      ssh_key = "${module.nodes.private_key}"
      role    = ["controlplane", "etcd"]
    },
    {
      address = "${module.nodes.addresses[1]}"
      user    = "${module.nodes.ssh_username}"
      ssh_key = "${module.nodes.private_key}"
      role    = ["controlplane", "etcd"]
    },
    {
      address = "${module.nodes.addresses[2]}"
      user    = "${module.nodes.ssh_username}"
      ssh_key = "${module.nodes.private_key}"
      role    = ["controlplane", "etcd"]
    },
    {
      address = "${module.nodes.addresses[3]}"
      user    = "${module.nodes.ssh_username}"
      ssh_key = "${module.nodes.private_key}"
      role    = ["worker"]
    },
    {
      address = "${module.nodes.addresses[4]}"
      user    = "${module.nodes.ssh_username}"
      ssh_key = "${module.nodes.private_key}"
      role    = ["worker"]
    },
    {
      address = "${module.nodes.addresses[5]}"
      user    = "${module.nodes.ssh_username}"
      ssh_key = "${module.nodes.private_key}"
      role    = ["worker"]
    },
  ]
}`

**Comment by yamamoto-febc** [comment]
Hi @rmccomb-bnet,

Your config looks good.
Does the same problem occur even if you exec the `rke` command directly?

**Comment by rmccomb-bnet** [comment]
I haven't tried it that way, let me do that and I'll elt you know

**Comment by rmccomb-bnet** [comment]
@yamamoto-febc That does work, the error I get is related to ssh but fixes itself once I re-run terraform again, weird.
