### ISSUE TITLE
Destroy of servers gets rke in to unresolvable state

### ISSUE THREAD

**Issue by justicel** [yamamoto-febc/terraform-provider-rke#11]
It appears that if you refresh your servers (say in this case in openstack) and they get a new IP list, RKE attempts to use the old server IPs no matter what. This leads to a 'terraform refresh' failing and with a '-refresh=false' it attempts to use the old IPs and gets stuck in a loop of 'still destroying', since the servers it is trying to reach no longer exist.

**Comment by justicel** [comment]
Also you can't even do a 'terraform destroy' because it still tries to destroy the cluster first.

**Comment by yamamoto-febc** [comment]
Hi @justicel , thank you for reporting.

As you pointed out, this provider will attempt to connect to the node IP address held in the state when running `terraform refresh/apply`.
If it can not connect to the node at that time, an error is returned.

So, I'm going to fix it to clear the state if node(s) can not be reached while running `refresh` or `destroy`.
