### ISSUE TITLE
Working with multiple jumphosts

### ISSUE THREAD

**Issue by blankdots** [yamamoto-febc/terraform-provider-rke#117]
This is more of a question, maybe feature request.
terraform version: `0.12.5`
terraform-provider-rke: `0.13.0`

I have the following setup:
```
                                                                             +-------+
                                                                             |       |
                                                               +------------>+  VM1  |
                                                               |             |       |
                                                               |             +-------+
                                                               |
+---------+        +----------------+       +------------------+             +-------+
|         |        |                |       |                  |             |       |
| Laptop  +------->+ Jump Host1     +------>+ Jump Host2       +------------>+  VM2  |
|         |        |                |       |                  ||            |       |
+---------+        +----------------+       +-------------------+            +-------+
                                                                |
                                                                |            +-------+
                                                                |            |       |
                                                                +----------->+ VM3   |
                                                                             |       |
                                                                             +-------+


```

I am spinning the VMs using https://github.com/dmacvicar/terraform-provider-libvirt in their own network from my laptop and I am trying to use the `terraform-provider-rke` from my laptop, however due to the two jump hosts I cannot use the rke provider because it cannot connect to `Jump Host2` directly.

I get the following error:
```
Error: 
Cluster must have at least one etcd plane host: please specify one or more etcd in cluster config

============= RKE outputs ==============

[info] Tearing down Kubernetes cluster
[info] [dialer] Setup tunnel for host [10.0.0.75]
[info] [dialer] Setup tunnel for host [10.0.0.102]
[info] [dialer] Setup tunnel for host [10.0.0.72]
[info] [dialer] Setup tunnel for host [10.0.0.52]
[warning] Failed to set up SSH tunneling for host [10.0.0.102]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [10.0.0.102:22]: Failed to connect to the bastion host [<jump_host2.name>:22]: dial tcp <jump_host2_ip>:22: connect: connection timed out
```

Doing a little digging into how the `bastion`  https://github.com/yamamoto-febc/terraform-provider-rke/blob/master/examples/full/example.tf#L62-L72 it does not seem to support the `ProxyCommand` the i have in my ssh config.

I did set: `ssh_agent_auth = true` - although that is only for the private key.

It seems there is a package that has such functionality: https://github.com/appleboy/easyssh-proxy.

Ultimately my questions: is there a way to use the `rke` provider from my laptop? Or did i miss something in my configuration?

**Comment by ulm0** [comment]
Have you tried to achieve this behavior with the plain rke binary? this provider is just a *wrapper* of rke itself, if something is supported on that side it should be supported here as well

**Comment by blankdots** [comment]
haven't tried. will probably not continue with that setup, thus closing this issue.
