### ISSUE TITLE
enable rke debug logs

### ISSUE THREAD

**Issue by bergur88** [yamamoto-febc/terraform-provider-rke#121]
it would be great to be able to enable rke debug logs to help with troubleshooting.

**Comment by bergur88** [comment]
exactly what i was looking for, thanks!

**Comment by ttk** [comment]
In the [latest version](https://github.com/rancher/terraform-provider-rke/blob/master/rke/provider.go#L15) it is now:

```
provider rke {
  debug = true
}
```

or via the env var `export RKE_DEBUG=1`
