### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by caleno** [yamamoto-febc/terraform-provider-rke#130]
Hey, 

I get an error when build both locally and with docker. 

```
go: error loading module requirements
make: *** [build] Error 1
```

Any ideas?

**Comment by yamamoto-febc** [comment]
Hi @caleno,

There were no errors in both the TravisCI test and the DockerHub build for the master branch.

Which version of Go are you using?
I'm using `go1.13.1 darwin/amd64` and `go1.13.1 linux/amd64`.

**Comment by caleno** [comment]
Ah, well I have an old version, maybe that is the problem. 

`go version go1.11.4 linux/amd64`

I'll update it and update with results. 

Thanks!

**Comment by caleno** [comment]
I managed to build with Docker with golang:1.13
