### ISSUE TITLE
Adding 'addons' causes cluster destroy/recreate rather than change

### ISSUE THREAD

**Issue by justicel** [yamamoto-febc/terraform-provider-rke#14]
If you add an additional addon or change the addon configurations in the right way, rather than resulting in a change to the cluster instead there is a 'destroy' and subsequent recreate issued to RKE. This results in a non-functioning cluster as there are leftovers such as etcd and similar.

**Comment by yamamoto-febc** [comment]
Good catch!
  
I missed that RKE already supports `addons` upgrades. 😱
> Add support for addons upgrades: https://github.com/rancher/rke/pull/680

So, I'm going to change `destroy/recreate` to `upgrade` when addons was changed. 😉
