### ISSUE TITLE
unable to remove hostname_override

### ISSUE THREAD

**Issue by insekticid** [yamamoto-febc/terraform-provider-rke#27]
when i set hostname_override = "node0" a then hostname_override = "" or remove hostname_override attribute in node, terraform will not remove this attribute :(

edit: manually removed in cluster-state in config maps

**Comment by yamamoto-febc** [comment]
I was able to reproduce this.
It seems to be a problem in the definition of the `rke_cluster` resource schema.
I'm going to fix it.
