### ISSUE TITLE
Support for Rancher upgrades?

### ISSUE THREAD

**Issue by insekticid** [yamamoto-febc/terraform-provider-rke#28]
Any plans for supporting Rancher upgrades via terraform? 

https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha-server-upgrade/
* ./rke_linux-amd64 etcd snapshot-save --name <SNAPSHOT.db> --config rancher-cluster.yml
* kubectl --kubeconfig=kube_config_rancher-cluster.yml set image deployment/cattle cattle-server=rancher/rancher:<VERSION_TAG> -n cattle-system

**Comment by insekticid** [comment]
@gaui I agree. 

Now there is new helm chart from Rancher team to add Rancher server to kubernetes cluster + cert manager tutorial.
https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/

 My way for now is terraform + rke + helm 
* https://github.com/yamamoto-febc/terraform-provider-rke
* https://github.com/mcuadros/terraform-provider-helm

**Comment by yamamoto-febc** [comment]
Hi @insekticid, sorry for delay.

I also agree with [@gaui's previous comment](
https://github.com/yamamoto-febc/terraform-provider-rke/issues/28#issuecomment-416012917).
We recommend to use with helm provider(same as your way :wink:).
So we don't have any plans to support for Rancher upgrades.

If you have any suggestions, please send PR.
