### ISSUE TITLE
Upgrade system images based on kubernetes_version

### ISSUE THREAD

**Issue by insekticid** [yamamoto-febc/terraform-provider-rke#29]
If I change kubernetes_version = "v1.11.1-rancher1-1" to kubernetes_version = "v1.11.2-rancher1-1" RKE should upgrade system images to latest versions

https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/k8s_defaults.go

**Comment by yamamoto-febc** [comment]
Hi @insekticid, Sorry for delay.  

RKE seems to allow only values defined by [k8sVersionsCurrent](https://github.com/rancher/rke/blob/v0.1.9/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go#L18-L22) for `kubernetes_version`. 

> - https://github.com/rancher/rke/blob/v0.1.9/cluster/defaults.go#L142-L145
> - https://github.com/rancher/rke/blob/v0.1.9/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go#L452-L458

For example, RKE v1.9 only the following values are allowed.

- `v1.9.7-rancher2-2`
- `v1.10.5-rancher1-2`
- `v1.11.1-rancher1-1`

If value of `kubernetes_version` can't found be in `k8sVersionsCurrent `, it uses `DefaultK8sVersion `.
> - https://github.com/rancher/rke/blob/v0.1.9/vendor/github.com/rancher/types/apis/management.cattle.io/v3/k8s_defaults.go#L11

So, upgrading system_images is possible as long as they are within the range of these values.

**Comment by gaui** [comment]
I think this can be closed. 😃

**Comment by yamamoto-febc** [comment]
Thank you @gaui. :smile:
I'm going to close this.
