### ISSUE TITLE
Dynamic node table

### ISSUE THREAD

**Issue by Joncak** [yamamoto-febc/terraform-provider-rke#3]
Hi, 

great work with the provider =D. 

Did you find a way to have dynamic number of nodes for this field ? 
 nodes = [
    {
      address      = "1.1.1.1"
      user         = "ubuntu"
      role         = ["controlplane", "etcd"]
      ssh_key_path = "~/.ssh/id_rsa"
      port         = 2222
    }

**Comment by yamamoto-febc** [comment]
Thank you for opening this question :)

Currently, there is no way to dynamically configure nodes:cry:.

However, Terraform core seems to be working on https://github.com/hashicorp/terraform/issues/7034 to support dynamic block configuration.

I think that we can solve this issue if dynamic block configuration is released.

**Comment by Joncak** [comment]
thanks @yamamoto-febc 

great work

**Comment by yamamoto-febc** [comment]
FYI: currently, terraform-provider-rke supports dynamic node configuration with `rke_node_parameter` resource.

> ref: [Add rke_node_parameter data source](https://github.com/yamamoto-febc/terraform-provider-rke/pull/8)
