### ISSUE TITLE
How can I specify list of ec2 IP addresses for dynamic creation

### ISSUE THREAD

**Issue by iamShantanu101** [yamamoto-febc/terraform-provider-rke#35]
Hi,

I have a multi-stage setup where I create n number of ec2 instances in terraform.

After that, I want to set up a rke cluster with those instances. So, how can I pass the ip's of those instances as a list here?

I came up with something like this but I am not sure if it will work:
```
data rke_node_parameter "nodes" {
  count   = 2

  address = "${element(aws_instance.rke-node.*.public_ip, count.index)}"
  user    = "ubuntu"
  role    = ["controlplane", "worker", "etcd"]
  ssh_key = "${file("~/.ssh/id_rsa")}"
}
```

**Comment by yamamoto-febc** [comment]
Hi @iamShantanu101,

You are right. :+1:

There are various ways to pass instance's IP addresses as list.
Your way is also one of the ways.

As another example, if you are using the latest version of Terraform(`v0.11.x`) you can write like a following:

```tf
locals {
  node_ip_list = "${aws_instance.rke-node.*.public_ip}"
}

data rke_node_parameter "nodes" {
  count   = "${length(local.node_ip_list)}"
  address = "${local.node_ip_list[count.index]}"
  user    = "ubuntu"
  role    = ["controlplane", "worker", "etcd"]
  ssh_key = "${file("~/.ssh/id_rsa")}"
}

resource rke_cluster "cluster" {
  nodes_conf = ["${data.rke_node_parameter.nodes.*.json}"]
}
```

**Comment by iamShantanu101** [comment]
@yamamoto-febc This doesn't work and my terraform version is `0.11.x`. Here's the error:

```
2 error(s) occurred:

* module.rke.local_file.kube_cluster_yaml: Resource 'rke_cluster.cluster' not found for variable 'rke_cluster.cluster.kube_config_yaml'
* module.rke.rke_cluster.cluster: nodes_conf: attribute supports 1 item as a minimum, config has 0 declared
```

**Comment by yamamoto-febc** [comment]
According to the error message, it seems to be a problem with the definition of `node_parameter`.
`rke_cluster.cluster` should have one or more declared nodes, but it have 0 declared.

Can you provide the all of tf files?

**Comment by yamamoto-febc** [comment]
Thank you for additional information. It seems that there is no problem.

Are definition of `aws_instance` and `rke_*` both in the same file or the same directory?

You should be able to use a list of IP addresses like `${aws_instance.rke-node.*.public_ip}` only if they are in the same module.

If not, you can use the [module's outputs](https://www.terraform.io/docs/modules/usage.html#outputs) or [terraform_remote_state](https://www.terraform.io/docs/providers/terraform/d/remote_state.html).

**Comment by iamShantanu101** [comment]
@yamamoto-febc Also, with your way to setting up `count` returns an error:

```
* module.rke.data.rke_node_parameter.nodes: data.rke_node_parameter.nodes: value of 'count' cannot be computed
```

**Comment by yamamoto-febc** [comment]
I think that the cause of the error is that you can not refer to `${aws_instance.rke-node.*.public_ip}`.

If you have the following module structure, you can use a like `${aws_instance.rke-node.*.public_ip}` to pass a list of IP addresses.

```console
# case: tf files are in the same module

$ tree .
.
├── aws_instance.tf   # contains aws_instance.rke-node definition
└── rke_cluster.tf    # contains rke_* definition
```

But, if you have the following module structure, you **can not** use it.

```console
# case: tf files are in the different module

$ tree .
.
├── aws
│   └── instance.tf # contains aws_instance.rke-node definition
└── rke_cluster.tf  # contains rke_* definition
```

Which is your module structure?

**Comment by iamShantanu101** [comment]
My module structure is:
```
➜  rke git:(master) ✗ tree
.
├── iam.tf
├── nodes.tf
├── outputs.tf
├── rke-setup.tf
├── variables.tf
└── vpc.tf
```

Where `nodes.tf` contains ec2 instance creation and `rke-setup` contains rke provisioner setup.

**Comment by yamamoto-febc** [comment]
Oh, sorry. I missed that [your comment has been updated](https://github.com/yamamoto-febc/terraform-provider-rke/issues/35#issuecomment-432109436).

> can we generate rancher-cluster.yml file from this as well? Considering we'd like to manage cluster with rke cli?

> My concern is: Will I get a rancher-cluster.yml file rendered after cluster gets created so that I can run rke commands with it?

We can generate yaml for running `rke` command.  
To generate it, please use `rke_cluster`'s `rke_cluster_yaml` attribute.

For example:

```hcl
resource "local_file" "rke_yaml" {
  filename = "${path.module}/rancher-cluster.yml"
  content = "${rke_cluster.cluster.rke_cluster_yaml}"
}
```

It generate `rancher-cluster.yml` file. 
After that, you can run `rke` command like as follows:

```bash
$ rke <subcommand> --config rancher-cluster.yml
```

**Comment by iamShantanu101** [comment]
It's working. Thanks @yamamoto-febc.
