### ISSUE TITLE
Wich version ?

### ISSUE THREAD

**Issue by solune** [yamamoto-febc/terraform-provider-rke#52]
#terraform-provider-rke_v0.7.0_x4
#target node on  rancherOS on 1.5.0
With this minimal config:
`
resource rke_cluster "cluster" {
  nodes = [
    {
      address = "${vsphere_virtual_machine.vm1.default_ip_address}"
      user    = "rancher"
      role    = ["controlplane", "worker", "etcd"]
    },
  ]
`
I have this error : 
* rke_cluster.cluster:
Unsupported Docker version found [18.06.1-ce], supported versions are [1.11.x 1.12.x 1.13.x 17.03.x]

With "ignore_docker_version = true" I have:
* rke_cluster.cluster:
[controlPlane] Failed to bring up Control Plane: Failed to create [kube-apiserver] container on host [10.35.20.127]: Error: No such image: rancher/hyperkube:v1.11.6-rancher1

With "kubernetes_version = "v1.12.5-rancher1-1" given on [https://github.com/rancher/types/blob/a3c9a8f4614922719729a05256e18f235e918622/apis/management.cattle.io/v3/k8s_defaults.go#L28](url) , I have:
expected kubernetes_version to be one of [v1.9.7-rancher2-2 v1.10.12-rancher1-1 v1.11.6-rancher1-1 v1.12.4-rancher1-1], got v1.12.5-rancher1-1

With kubernetes_version = "v1.12.4-rancher1-1" , I have:
[controlPlane] Failed to bring up Control Plane: Failed to create [kube-apiserver] container on host [10.35.20.126]: Error: No such image: rancher/hyperkube:v1.12.4-rancher1

Which version should I use ?

**Comment by yamamoto-febc** [comment]
Hi @solune, 

terraform-provider-rke v0.7.0 uses `rancher/types`@1e7d94553cfa .
(https://github.com/yamamoto-febc/terraform-provider-rke/blob/0.7.0/go.mod#L61) 

And `k8sVersionsCurrent` in `rancher/types`@1e7d94553cfa is this:
https://github.com/rancher/types/blob/1e7d94553cfaccb6b0b76af7c02c46732cee4597/apis/management.cattle.io/v3/k8s_defaults.go#L18-L24

So expected Kubernetes versions are:
- `v1.9.7-rancher2-2`
- `v1.10.12-rancher1-1`
- `v1.11.6-rancher1-1`
- `v1.12.4-rancher1-1`

And I tried running this provider with following tf file:

```hcl
resource rke_cluster "cluster" {
  ignore_docker_version = true
  kubernetes_version    = "v1.12.4-rancher1-1"

  nodes = {
    address = "${var.ipaddress}"
    user    = "rancher"
    role    = ["etcd", "controlplane", "worker"]
    ssh_key = "${var.ssh_key}"
  }
}
```

But I couldn't reproduce your reported error.  

And your error message is "error: no such image: rancher/hyperkube:v1.11.6-rancher1",
so I think that your VM can not connect to DockerHub.

Is your VM's network setting right? Can your VM connect to DockerHub?

**Comment by solune** [comment]
Thanks it works now
