### ISSUE TITLE
rke 0.1.17

### ISSUE THREAD

**Issue by insekticid** [yamamoto-febc/terraform-provider-rke#68]
https://github.com/rancher/rke/releases/tag/v0.1.17

**Comment by yamamoto-febc** [comment]
Hi @insekticid! 
Thank you for let me know.

Currently, terraform-provider-rke focuses on RKE `v0.2.x` only.
Do you have a use-case that uses `v0.1.x` instead of `v0.2.x`? Please let me know if you have.

**Comment by insekticid** [comment]
yes, it is lates stable, so this is only one valid way, how to upgrade cluster and get latest security patches

**Comment by yamamoto-febc** [comment]
Oh... yes, you are right.

OK, current master branch is aim to RKE v0.2.x.
So I'm going checkout v0.1.x branch from previous commits on master.

Thanks again @insekticid for your notification👍

**Comment by yamamoto-febc** [comment]
We have just released [v0.9.0](https://github.com/yamamoto-febc/terraform-provider-rke/releases/tag/0.9.0).

This version is using RKE v0.1.17.
Please try it:+1:

**Comment by insekticid** [comment]
it works! thx 🎉
