### ISSUE TITLE
RKE addon usage

### ISSUE THREAD

**Issue by ChrisMcKee** [yamamoto-febc/terraform-provider-rke#72]
https://github.com/yamamoto-febc/terraform-provider-rke/blob/master/examples/rancher_server_ssl_passthrough/example.tf

Rancher moved away from using the addon system (though it stills works) even though they say it should only work till 2.0.8 (Important: RKE add-on install is only supported up to Rancher v2.0.8)

https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/migrating-from-rke-add-on/

**Comment by ChrisMcKee** [comment]
![image](https://user-images.githubusercontent.com/83597/54196891-6e800400-44ba-11e9-88ba-1b7090891965.png)

Once RKE is completed the next steps would have to be taken using https://www.terraform.io/docs/providers/helm/index.html using the rke_cluster..kube_config

**Comment by ChrisMcKee** [comment]
The setup goes to pot of course if using helm/k8 terraform providers and a local network as neither provider handles bastion hosts 😱

**Comment by ChrisMcKee** [comment]
So for a bastion, using https://github.com/stefansundin/terraform-provider-ssh/releases , seems the only way around dealing with all this helm stuff.

```
provider "ssh" {}

data "ssh_tunnel" "rancher" {
  user        = "ubuntu"
  host        = "x.x.x.x.x"
  private_key = "${file("./bastion-key.pem")}"

  # use port 0 to request an ephemeral port (a random port)
  local_address  = "localhost:6443"
  remote_address = "${module.nodes.private_addresses[0]}:6443"
}

provider "kubernetes" {
  host     = "https://127.0.0.1:6443"
  username = "${rke_cluster.cluster.kube_admin_user}"

  client_certificate     = "${rke_cluster.cluster.client_cert}"
  client_key             = "${rke_cluster.cluster.client_key}"
  cluster_ca_certificate = "${rke_cluster.cluster.ca_crt}"
}

resource "kubernetes_service_account" "tiller" {
  metadata {
    name      = "tiller"
    namespace = "kube-system"
  }

  automount_service_account_token = true
}

resource "kubernetes_cluster_role_binding" "tiller" {
  metadata {
    name = "tiller"
  }

  role_ref {
    kind      = "ClusterRole"
    name      = "cluster-admin"
    api_group = "rbac.authorization.k8s.io"
  }

  subject {
    kind = "ServiceAccount"
    name = "tiller"

    api_group = ""
    namespace = "kube-system"
  }
}

#NGINX/HELM

provider "helm" {
  debug          = true
  install_tiller = false

  kubernetes {
    host     = "https://127.0.0.1:6443"
    username = "${rke_cluster.cluster.kube_admin_user}"

    client_certificate     = "${rke_cluster.cluster.client_cert}"
    client_key             = "${rke_cluster.cluster.client_key}"
    cluster_ca_certificate = "${rke_cluster.cluster.ca_crt}"
  }
}

data "helm_repository" "stable" {
  name = "stable"
  url  = "https://kubernetes-charts.storage.googleapis.com"
}

resource "helm_release" "nginx-ingress" {
  depends_on = ["kubernetes_cluster_role_binding.tiller"]
  name       = "nginx-ingress"
  repository = "${data.helm_repository.stable.metadata.0.name}"
  chart      = "stable/nginx-ingress"

  #wait = false
  namespace = "kube-system"

  values = [
    <<-EOF
        rbac:
          create: true
        controller:
          replicaCount: 2
          service:
            annotations: 
              service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      EOF
    ,
  ]
}

data "kubernetes_service" "rancher-ingress" {
  metadata {
    name      = "${helm_release.nginx-ingress.name}-controller"
    namespace = "${helm_release.nginx-ingress.namespace}"
  }

  depends_on = ["helm_release.nginx-ingress"]
}

### HELM

variable "kubesysns" {
  default = "kube-system"
}

## HELM

data "helm_repository" "rancher-latest" {
  name = "rancher-latest"
  url  = "https://releases.rancher.com/server-charts/latest"
}

resource "helm_release" "cert-manager" {
  name         = "cert-manager"
  repository   = "${data.helm_repository.stable.metadata.0.name}"
  chart        = "stable/cert-manager"
  wait         = false
  force_update = true
  namespace    = "kube-system"
  version      = "v0.5.2"
}

resource "helm_release" "rancher" {
  name         = "rancher"
  repository   = "${data.helm_repository.rancher-latest.metadata.0.name}"
  chart        = "rancher-latest/rancher"
  wait         = false
  force_update = true
  namespace    = "cattle-system"

  set {
    name  = "hostname"
    value = "rancher.mysrv.eu"
  }

  set {
    name  = "ingress.tls.source"
    value = "rancher"
  }

  depends_on = ["helm_release.nginx-ingress"]
}

```

I should add the above fails with helm errors.

**Comment by ChrisMcKee** [comment]
_failure may be related to the order of things https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-init/troubleshooting/ _

**Comment by yamamoto-febc** [comment]
Hi @ChrisMcKee,

Thank you for letting me know this issue.
Also, thanks for trying to install in combination with the helm provider!

I think that how to install Rancher server by combination with the helm provider should be documented, and be added examples on this repo.

I'd like to try this, but, unfortunately, I don't have enough time right now.

So if you get good result with the combination of the helm provider and the RKE provider, please post PR:+1:

**Comment by ChrisMcKee** [comment]
There's a ticket on the RancherClient to add in RKE; and to add a helm provider in the same way that it handles the kubectl proxying so RKE can handle the full job; which would be ideal.

**Comment by ChrisMcKee** [comment]
I ended up deploying k8 via rke and storing state. Then generating the helm commands from template into scripts.
It seems an arse about face way of doing things but unfortunately terraform doesnt really deal with the fact that the calls to helm you need to make are different between an upgrade and an installation; and the `helm upgrade -i` flag which supposedly will install if not present does not behave as you'd expect.

Sometimes it's easier to not fight the flow of the river.
