### ISSUE TITLE
RKE 0.2.0 released

### ISSUE THREAD

**Issue by insekticid** [yamamoto-febc/terraform-provider-rke#76]
RKE 0.2.0 released

**Comment by ChrisMcKee** [comment]
https://github.com/rancher/rke/releases/tag/v0.2.0

**Comment by ChrisMcKee** [comment]
On creating a cluster RKE now creates a state file cluster.rkestate
It bungs certs and all the stuff that used to be backed up in the cluster there with a view that it won't be available in the cluster afterwards.
So now there's a state file to deal with ... they drive you nuts

**Comment by yamamoto-febc** [comment]
Thank you @insekticid.

I noticed to RKE v0.2.1 has also been released.
https://github.com/rancher/rke/releases/tag/v0.2.1

So I'm going to upgrade to use v0.2.1.

@ChrisMcKee That's right, RKE creates state file `cluster.rkestate` now.

I think this provider should not deal with the details of rkestate.
So this provider hold that as [`rke_state`](https://github.com/yamamoto-febc/terraform-provider-rke/blob/v1.0.0-beta.1/rke/schema.go#L1628-L1632) on tfstate and it will be restored as a file when `terraform apply/refresh` is executed.

**Comment by ChrisMcKee** [comment]
@yamamoto-febc yeah tbh when I wrote it I hadn't searched the code for references to it yet; That makes sense. Without it rke tries to redeploy with new certs (horrible change imo). 
They're working on their own btw https://github.com/rancher/terraform-provider-rancher2/blob/master/website/docs/r/cluster.html.markdown

**Comment by invidian** [comment]
We are on [v0.2.2](https://github.com/yamamoto-febc/terraform-provider-rke/pull/83) now, so this can be closed I guess.

**Comment by yamamoto-febc** [comment]
I'm going to close this. Thank you guys👍
