### ISSUE TITLE
Error should include more than "Cluster must have at least one etcd plane host" when running terraform apply

### ISSUE THREAD

**Issue by pib** [yamamoto-febc/terraform-provider-rke#9]
I'm using Terraform 0.11.7 and the new 0.3.0 rke provider, and when attempting to use nodes_conf it seems that it always returns an error when trying to apply

```
Error: Error applying plan:

1 error(s) occurred:

* rke_cluster.cluster: 1 error(s) occurred:

* rke_cluster.cluster: Cluster must have at least one etcd plane host
```

I get the error in my own config I was working on as well as in the simple example config from https://github.com/yamamoto-febc/terraform-provider-rke/blob/master/examples/multiple_nodes/example.tf

`terraform plan` doesn't complain, and I see that the error is actually from RKE itself, so it seems that the config isn't actually making its way to RKE when specified via nodes_conf.

**Comment by pib** [comment]
Oh! Actually it's simpler than that!

It just never works even if `nodes` is used instead of `nodes_conf`:

```
resource "rke_cluster" "cluster" {
  nodes = [
    {
      address = "1.2.3.4"
      user = "rancher"
      role = ["controlplane", "etcd", "worker"]
      ssh_key = "${file("~/.ssh/id_rsa")}"
    }
  ]

}
```
Gives the same error.

**Comment by pib** [comment]
Oh, once again it seems it's even a bit simpler. That is just the final error that rke emits, but it looks like what is actually happening is it is failing to connect to the specified host(s) and then removing them from the list, but none of that is included in the output of `terraform apply`.

**Comment by yamamoto-febc** [comment]
Hi @pib,

Thank you for reporting.

I just created PR(#10) to fix it.
After #10 merged, `terraform apply` logs will be as following:

```
$ terraform apply

Error: Error applying plan:

1 error(s) occurred:

* rke_cluster.cluster: 1 error(s) occurred:

* rke_cluster.cluster: 
Cluster must have at least one etcd plane host

...

============= RKE outputs ==============

[info] Building Kubernetes cluster
[info] [dialer] Setup tunnel for host [192.2.0.1]
[warning] Failed to set up SSH tunneling for host [192.2.0.1]: Can't retrieve Docker Info: error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: Failed to dial ssh using address [192.2.0.1:22]: dial tcp 192.2.0.1:22: connect: operation timed out
[warning] Removing host [192.2.0.1] from node lists

========================================
```

**Comment by pib** [comment]
Awesome, thanks!
